### ISSUE TITLE
API requests hang indefinitely

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/forecast-ruby#10]
We received this from an API user:

> I'm using your forecast_io ruby gem in Rails: https://rubygems.org/gems/forecast_io
> 
> When I call the API, it hangs indefinitely:
> 
> ```ruby
> ForecastIO.forecast(latitude, longitude, time: start_time, params: { exclude: 'flags,minutely,hourly,alert' })
> ```
> 
> Let me know if I can do anything else to provide more info, or if you know what the problem is.

We're not experiencing any issues directly with the API. Is there any cause that might be specific to the library or to the client that I should request from them?

**Comment by czarneckid** [comment]
It'd be helpful to know versions for Ruby, the gem, and Rails, that they are currently using. It would also be helpful to know if they're using the default HTTP adapter used by Faraday in the gem, which is Net::HTTP or if they're using another adapter like Typhoeus. If they are using the default Net::HTTP adapter, I believe the default HTTP read timeout is 60 seconds, so I would expect that a request might hang for that long and be killed, not indefinitely.

**Comment by ironwallaby** [comment]
Thanks! I'll check with them.

**Comment by joevandyk** [comment]
@ironwallaby @czarneckid it would be nice to be able to easily customize the timeout with this gem.

**Comment by czarneckid** [comment]
@joevandyk You should be able to do this via Faraday. See the following [issue](https://github.com/lostisland/faraday/issues/417) for details on how to add this customization.

**Comment by jon-eckstein** [comment]
@czarneckid Looking at the issue you linked to above, I would still have to monkey patch the forecast.io gem to achieve a configurable timeout correct? It looks like Faraday only allows setting the timeout params on connection creation.

**Comment by kulte** [comment]
It would just be nice if you added `timeout` as an option in Configuration. I went digging in the Faraday codebase for this, and it's just annoying to try to figure out how I'd pull this off... and yes, like @jon-eckstein said, it looks like it might require a money patch, which I'd like to avoid. Thanks 🙏

**Comment by kulte** [comment]
@ironwallaby I just added this PR which should completely fix the issue. It would be great to get this merged ASAP so we (and everyone) can start using timeouts if we so choose! Thanks!!
